//! Build script for `rieko-api` (WP5.1 / RIEKO-AUDIT-009).
//!
//! The v1 delivery is a single binary: the Rust `serve` command must serve the
//! frontend with no external `dist` directory and no Node.js at runtime. To do
//! that the built assets are embedded into the binary at compile time.
//!
//! This script:
//! * Locates the built assets under `frontend/dist` (repo root).
//! * If present, generates `$OUT_DIR/ui_assets.rs` — a `&[(&str, &[u8])]` table
//!   of every file embedded via `include_bytes!` — and sets the
//!   `rieko_ui_embedded` cfg so the crate compiles the embedded UI in.
//! * If absent in a **release** build, fails the build with a clear message.
//! * If absent in a **debug** build, leaves the crate in dev mode (the optional
//!   `--static-dir` flag then serves filesystem assets, as before).

use std::env;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let repo_root = manifest
        .parent()
        .and_then(Path::parent)
        .expect("rieko-api is two levels below the workspace root");
    let dist = repo_root.join("frontend").join("dist");
    let index = dist.join("index.html");

    let profile = env::var("PROFILE").unwrap_or_default();
    let is_release = profile == "release";

    println!("cargo:rerun-if-changed={}", dist.display());
    println!(
        "cargo:rerun-if-changed={}",
        repo_root.join("frontend").display()
    );
    println!("cargo:rustc-check-cfg=cfg(rieko_ui_embedded)");

    if index.exists() {
        let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
        let mut files = Vec::new();
        collect_files(&dist, &mut files);
        files.sort();

        let mut source = String::from(
            "// Generated by rieko-api/build.rs — embedded frontend assets (WP5.1).\n",
        );
        source.push_str("#[allow(clippy::all)]\n");
        source.push_str("pub static ASSETS: &[(&str, &[u8])] = &[\n");
        for file in &files {
            let rel = file
                .strip_prefix(&dist)
                .expect("file collected from dist")
                .to_string_lossy()
                .replace('\\', "/");
            source.push_str(&format!(
                "    ({rel:?}, include_bytes!({:?})),\n",
                file.to_string_lossy()
            ));
        }
        source.push_str("];\n");
        std::fs::write(out_dir.join("ui_assets.rs"), source)
            .expect("writing generated ui_assets.rs");
        println!("cargo:rustc-cfg=rieko_ui_embedded");
    } else if is_release {
        panic!(
            "release build requires a frontend build: frontend/dist/index.html is missing. \
             Run `npm ci && npm run build` in frontend/ first (RIEKO-AUDIT-009 / WP5.1)."
        );
    }
    // Debug builds without a UI build compile in dev mode: the optional
    // --static-dir flag serves filesystem assets instead.
}

fn collect_files(dir: &Path, out: &mut Vec<PathBuf>) {
    for entry in std::fs::read_dir(dir).expect("reading dist directory") {
        let entry = entry.expect("reading dist entry");
        let path = entry.path();
        if path.is_dir() {
            collect_files(&path, out);
        } else {
            out.push(path);
        }
    }
}
